spring:
  application:
    name: spring-auth

  datasource:
    url: jdbc:postgresql://localhost:5432/spring-auth
    username: spring-auth
    password: spring-auth

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

app:
  bootstrap:
    admin-username: admin
    admin-password: admin
    admin-email: admin@example.com
  security:
    jwt:
      ttl-seconds: 3600
      issuer: spring-auth

jwt:
  public:
    key: classpath:publicKey.pem
  private:
    key: classpath:privateKey.pem
