spring:
  application:
    name: spring-auth

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/spring-auth}
    username: ${DB_USERNAME:spring-auth}
    password: ${DB_PASSWORD:spring-auth}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

app:
  bootstrap:
    admin-username: admin
    admin-password: admin
    admin-email: admin@example.com
  security:
    jwt:
      ttl-seconds: 3600
      issuer: spring-auth

jwt:
  public:
    key: classpath:publicKey.pem
  private:
    key: classpath:privateKey.pem
